### ISSUE TITLE
?missing? query in Bielefeld_DMP views.xml 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo-catalog#1]
Is there a reason why 
https://github.com/rdmorganiser/rdmo-catalog/blob/cef6ac3363d97d3d1ccb2b45c03c22d4a1b84b22/views.xml#L39
does not query  {{ values.project.additional_rdm_policy.requirements }} ?

**Comment by triole** [comment]
Seems outdated. Therefore closing.
