### ISSUE TITLE
multiple entries of attributes in domain/rdmo.xml

### ISSUE THREAD

**Issue by Bassbiest** [rdmorganiser/rdmo-catalog#10]
The file contains multiple entries of maybe all attributes, except the very first one. I tested at random, so it might not apply to all of them. The highest multiple I found so far was four times the same attribute.

Each attribute uses 7 lines of code, there are about 125 attributes for the questions + parent attributes. That should be about 150 attributes in total, which results in about 1050 lines of code, but the file has almost 5000 lines of code.

**Comment by jmfrenzel** [comment]
I can reproduce, that this is an bug in the export of rdmo. https://github.com/rdmorganiser/rdmo/issues/126

**Comment by jmfrenzel** [comment]
In rdmo the cause of the problem has been fixed https://github.com/rdmorganiser/rdmo/commit/01346bab82b34c945e2ea9704cdd7f90db4849d7

**Comment by jmfrenzel** [comment]
Still need to have a clean xml in this repo

**Comment by triole** [comment]
The domain.xml was updated. It is much shorter now and should no longer have duplications.
