### ISSUE TITLE
optionsets in collection questionsets

### ISSUE THREAD

**Issue by mwagner12** [rdmorganiser/rdmo-catalog#107]
Prerequisite: I typically define new catalogs using the xml upload in RDMO.
If I include an optionset (e.g. accessible via radio buttons) to a questionset with a collection the choice of the option for a specific dataset won't be saved (currently using RDMO 1.5.5). If I skip is_collection=true for the questionset, the same constellation works fine. Is this a bug and possibly already solved in RDMO 1.6? Or is it necessary to add something specific to the xml file to be uploaded to RDMO?

**Comment by jochenklar** [comment]
Can you provide the xml for the questionset? Questionsets cannot have optionsets, only questions have optionsets.

**Comment by mwagner12** [comment]
Right, my mistake, I mean optionsets in questions, not in questionsets.
In the meantime I found my error (has nothing to do with the version of RDMO nor is it a bug): Initially I assigned attributes to questions containing the section and questionset for the sake of traceability. But, if I want to use the same dataset collection in a question in another questionset and/or section, I must use an attribute path that includes the original path until the questionset with the collection definition. After the compulsory part I can add an arbitrary long path. Side note: Each questionset pointing to the same collection must have the same attribute (that I already knew).
Working attribute examples:
- x/y/questionset1 -> attribute for questionset with collection definition
- x/y/questionset1/id -> necessary additional attribute (for RDMO 1.5, in RDMO 1.6 automatically inserted(?))
- x/y/questionset1/question1 -> attribute for a question referring to the collection
- x/y/questionset1/questionset2/question1 -> example attribute for a question in another questionset referring to the same collection, but with a bit of traceability to the superordinate questionset
Non-working attribute example:
- x/y/questionset2/question1 -> if questionset2 has the same attribute like questionset1 (pointing to the same dataset collection) the content of this question isn't saved

**Comment by jochenklar** [comment]
This we actually fixed in RDMO 1.6. Now attributes of one questionset don't need to be "under" the attribute assigned to questionset. Also the implicit `id` attribute is now explicit, so instead of `project/dataset`, you need to assign `project/dataset/id` to the questionset. The migration to 1.6 handles that automatically for attributes of questionsets which are a collection. The code for this is here: https://github.com/rdmorganiser/rdmo/blob/master/rdmo/questions/migrations/0065_data_migration.py#L10

**Comment by mwagner12** [comment]
Perfect! I tried omitting /id and other attribute paths for questions in RDMO 1.6 and all works. Thanks!
