### ISSUE TITLE
Add two questions: Permanent contact person of the data owner

### ISSUE THREAD

**Issue by ClaraRosalie** [rdmorganiser/rdmo-catalog#110]
**Describe the request**  
A question is to be added which addresses the role of a permanent contact for the data. 
There must exist a person filling this role which is relevant most likely after the end of a project. 
So this role is also more permanent compared to a data manager which is likely filled by a person with a non-permanent contract (see     
existing question `general/project-partners-partner/contact` covering general data management role during the project). 

We suggest to add two new questions about the permanent project owner/data owner to the 
question set `storage-and-long-term-preservation/long-term-preservation-datasets`. 
Two new attributes need to be added as well.

**Propose what exactly should be changed**  
add two questions and two attributes as below

**Proposed setting or content**   
1. **question:** `storage-and-long-term-preservation/long-term-preservation-datasets/responsible_person_name`  
   **attribute:** `project/dataset/preservation/responsible_person/name`
   **question text en:** ~~"Who is the permanent project owner/data owner who can decide on the data after the researcher leaves? Please enter the name."~~"Who is the long-term contact person who can make decisions about the data? Please specify the name." (changed see #111 )
   **help text en:** ~~"Examples of these decisions include data access and authorization, the optimization of storage space after a certain retention period, or the transfer of authority to a new contact person. Such decisions are necessary, for example, in the event of a loss of access data, a new access request or the departure of the previous contact person." (changed see #111 )
   **question text de:** ~~"Wer ist der dauerhafter Besitzer der Daten, der nach dem Weggang des Forschenden über die Daten entscheiden kann? Bitte geben Sie den Name an."~~"Wer ist der langfristige Ansprechpartner, der über die Daten entscheiden kann? Bitte geben Sie den Name an." (changed see #111 )
   **help text de:** ~~"Eine ähnliche Fragestellung ist, was passiert bei Verlust der Zugangsdaten oder beispielsweise beim Ausscheiden/Ruhestand des Lehrstuhlinhabers? Dies sollte später über einen Workflow mit bedacht werden."~~"Eine ähnliche Fragestellung ist, was passiert bei Verlust der Zugangsdaten oder beispielsweise beim Ausscheiden/Ruhestand des Lehrstuhlinhabers? Dies sollte später über einen Workflow mit bedacht werden."~~"Beispiele hierfür sind die Vergabe von Zugangsdaten/Zugangsberechtigungen, die Optimierung des Speicherplatzes nach einer gewissen Aufbewahrungsfrist oder die Übergabe der Befugnisse an einen neuen Ansprechpartner. Solche Entscheidungen sind beispielsweise bei einem Verlust von Zugangsdaten, bei einer neuen Zugangsanfrage oder beim Ausscheiden des bisherigen Ansprechpartners erforderlich." (changed see #111 )

2. **question:** `storage-and-long-term-preservation/long-term-preservation-datasets/responsible_person_email`  
   **attribute:** `project/dataset/preservation/responsible_person/email`
   **question text en:** "Please provide the email address of the permanent owner of the data requested above."
   **help text en:**
   **question text de:** "Bitte geben Sie die E-Mail-Adresse des oben gefragten dauerhaften Besitzer der Daten an."
   **help text de:**

**Comment by Zack-83** [comment]
Is "owner" / "Besitzer" the right word? Or better "the responsible"? The legal status of data is not so clear...

**Comment by Zack-83** [comment]
I find it a good suggestion and have proposed some minor changes
