### ISSUE TITLE
Optionset not set in question after import (fodako)

### ISSUE THREAD

**Issue by FabianHamm** [rdmorganiser/rdmo-catalog#12]
Hello,

I have just installed rdmo (0.14.6) and imported the RDMO Catalog (rdmorganiser) according to the import order specified in the readme. Answering the questions of the RDMO catalog works fine.

I then imported the catalogs in the fodako folder (according to instructions in the pdf), however it seems that some questions are missing the correct optionset entry, so that they can not be answered. Of course selecting the right optionset manually fixes the problem.

Is there a specific import order required, is this a bug or why is the optionset entry not imported for some questions?

Thank you

**Comment by jochenklar** [comment]
Hi, thanks for reporting. Yes, there is an order to consider, we might need to document that better. First the domain and the options then the questions, since they use both Attribtes and OptionSets.

**Comment by FabianHamm** [comment]
Thanks for the reply. i just saw that the optionset elements in catalog_dfg.xml have entries with different uri than the rdmo options in my installation. 

E.g. changing this

`<optionset dc:uri="https://ed45a26fb17322518ab44517596c99f815c6df14.rdmo/options/other_requirements_options"/>`

to this

`<optionset dc:uri="https://rdmorganiser.github.io/terms/options/other_requirements_options"/>`

makes the import work ...

**Comment by triole** [comment]
Thanks for reporting and even delivering the solution. The xml files are fixed. I am going to have look at the sanitizer as well. But this ticket can be closed.
