### ISSUE TITLE
missing quotes in HTML <a> target Attribute

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo-catalog#15]
There are multiple HTML <a> target attributes in questions text and help text in `rdmorganizer/questions/*.xml` which miss a leading  `"` or `&quot;` 

**current**
`target=_blank&quot;`

**expected** 
`target=&quot;_blank&quot;` or `target="_blank"`

**files being affected**

```bash
> grep -rinl target=_ 
rdmorganiser/questions/rdmo.xml  
rdmorganiser/questions/fhpshort.xml  
rdmorganiser/questions/snf.xml  
rdmorganiser/questions/dcc.xml 
shared/fodako/catalog_all.xml  
shared/fodako/catalog_dfg.xml 
shared/fodako/catalog_ratswd_dfg.xml  
shared/fodako/catalog_economics_dfg.xml  
shared/fodako/catalog_edu_dfg.xml
shared/ub_fau_erlangen_nuernberg/DFG_Editionen/DFG_editions.xml
shared/ub_fau_erlangen_nuernberg/eHum_H2020/eHum_H2020_Fragebogen.xml
shared/nfdi4ing/rdmo_mechanical_engineering/catalog_mb_20190124.xml
```

Ref.   
https://www.w3schools.com/tags/att_a_target.asp

**Comment by jmfrenzel** [comment]
My guess is, that the bug was introduced via export of rdmo using an erlier version of the code. 
With the current rdmo-v1.0.6 export of questions containing `target="_blank"` are containing that opening `"` in the output xml.

**Comment by triole** [comment]
I added the missing quotation marks and checked against the latest RDMO version. Imports went fine and exports rendered correctly. The current version does not seem to be affected.
