### ISSUE TITLE
Dublicate question text .../funder_policy

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo-catalog#16]
rdmo.xml at  https://github.com/rdmorganiser/rdmo-catalog/commit/7786db088128fe51f84c280a4e7043a0d44470da  all texts from `<question dc:uri="https://rdmorganiser.github.io/terms/questions/rdmo/legal-and-ethics/sensitive-data-other/funder_policy">` have been copied over to a new question `<question dc:uri="https://rdmorganiser.github.io/terms/questions/rdmo/general/funding-funder/funder_policy">`. So there exist two times the same question in this catalog, although in different sections and each time linked to different attributes. This is a bit clumsy, because it confuses the user at least in the "Show answers" section. 

Moreover, the Question text for `<question dc:uri="https://rdmorganiser.github.io/terms/questions/rdmo/legal-and-ethics/sensitive-data-other/funder_policy">` could be improved pointing the user towards the section's topic "sensitive data".

**Comment by triole** [comment]
Thanks for spotting and reporting the duplicate. I removed the question under `sensitive-data`. 

Fixed in commit https://github.com/rdmorganiser/rdmo-catalog/commit/3d7caaa338e1e86814ed34967866885f2031f1ea
