### ISSUE TITLE
SMP feedback

### ISSUE THREAD

**Issue by jcolomb** [rdmorganiser/rdmo-catalog#166]
As usual with forms, it is long and will scare people away... Anyway to include some shortcuts, or some prioritisation of the question (maybe question to answer really early, why others may be answered later?)

I think some questions are missing or should be rephrased:
`Are your sure that no suitable software exists with the functionality your are planning?`
- there is probably not a software doing exactly what is meant for the planned software, but there is probably lot of software or code that are related. the question should more be: what software/code have similar purposes, what is missing in these products for you to use it.

`Who are the project participants that deal with this software?`
- I think it would be good to have more questions about the community around the planned software: who are the end-users, who are contributors (developers and non-developers), if communities already exists (maybe around another similar project) and how it is planned to participate in these communities... 
- (linked to publication part) How do you plan to have users to the software, do you have plans to grow the community of users beyond the initial participants.

`How long should the software remain usable?`

- how will the software be maintained after the project, what strategy is used to make the software usable on the long term (containerisation, preservation)

**Comment by yvgrossmann** [comment]
Thanks a lot @jcolomb for the feedback regarding your SMP catalogue!

1.
A good point, thank you! I have expanded the question to include this aspect as well.

2.
* We have tried to give space for such aspects with the question "Are there requirements regarding the software development form other parties?". to give space for such aspects. Multiple criticism of the SMP catalogue was always the large number of questions. Therefore, we have tried to reduce as much as possible and offer such questions with multiple answer directions (e.g. community or third-party funder). I have therefore added it to the auxiliary text for this question.
* The second question is equally exciting. For this I would have suggested the existing question "Will users have the possibility to contribute to your software?" in the Release and Publish section.

3.
Thank you, very good point. I added it to the question "Publicly Available".

Iam working in some other feedback right now. I will try to push my revised version of the SMP catalogue to the community soon. The changes mentioned here will be included there.
