### ISSUE TITLE
Horizon Europe catalog: Move catalog description to designated xml entry 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo-catalog#180]
Horizon Europe catalog should provide a help text. 

Currently the designated xml entry is empty and thus will provide the user of rdmo with information on the catalog in the catalog selection for a project.  see
https://github.com/rdmorganiser/rdmo-catalog/blob/823dd7ce997779c625cfb089f238471356bdd9b7/rdmorganiser/questions/horizon-europe.xml#L9

I propose to move the text  of help text the first question set for the Horizon Europe catalog to the catalog help text 
https://github.com/rdmorganiser/rdmo-catalog/blob/823dd7ce997779c625cfb089f238471356bdd9b7/rdmorganiser/questions/horizon-europe.xml#L43

**Comment by Zack-83** [comment]
Where is this text supposed to appear? I agree that "it would be nice" to add something, but the proposed text is far too long.
