### ISSUE TITLE
question_questionset_head_help calls wrong language for verbose name

### ISSUE THREAD

**Issue by sa-wetter** [rdmorganiser/rdmo-catalog#200]
Hi, this is my first bug report so please be kind. 
I am going through the DFG_v5 catalog and found a bug which puzzles me. The head help of question "is existing data reused?" uses a German word in an English sentence: 
<Please fill out the form for each Datensatz... >
Also the the green button reads "add Datensatz" which should be changed too.

However, going the next question which reads "Data types and processing" the head help is grammatically correct. 
When changing the language to German there are no errors. I had checked because I had assumed an accidental language swap but that is not the case. I believe the error could be here somewhere  -> /project_questions_questionset_head_help.html

I hope this information helps somewhat.

Best,
Sarah

![fill_in_form_for_Datensatz](https://github.com/rdmorganiser/rdmo/assets/141029341/b6b5acdc-a183-49de-9878-8a45fbdb0d10)
![fill_in_form_for_dataset](https://github.com/rdmorganiser/rdmo/assets/141029341/c7ef2628-8380-496e-8ea5-06938fb7a999)

**Comment by sa-wetter** [comment]
thanks for looking into this, @jochenklar !

**Comment by Zack-83** [comment]
solved through #201
