### ISSUE TITLE
Rephrase question set for DFG v5 catalog due to vagueness

### ISSUE THREAD

**Issue by sa-wetter** [rdmorganiser/rdmo-catalog#203]
Hi,

I'd like to make two suggestions for existing 'question sets' in the DFG v5 catalog. 

 In the section "long-term data accessibility", the question set simply reads "when available" which is also visible in the drop down overview of the catalog. How about changing the question set to "Data availability"? This would get rid of the vagueness if a person is filling out the section who has not reached that question but can see the preview on the right hand side of the screen. (see attached screenshot)
<img width="1286" alt="when_available" src="https://github.com/rdmorganiser/rdmo-catalog/assets/141029341/91eb46a8-5407-4983-ad25-8cb1b1cae3d9">

Similarly, the German "wann nutzbar" is equally vague. Here, "(zeitliche) Verfügbarkeit" could be better suited for section "Dauerhafte Zugänglichkeit".
<img width="976" alt="wann_nutzbar" src="https://github.com/rdmorganiser/rdmo-catalog/assets/141029341/9b12409d-9a2f-492d-b945-fc7b1bfd3ce9">

Let me know what you think.

Best,
Sarah

**Comment by Zack-83** [comment]
@sa-wetter Hier ist die Liste der Dateien, wo der Titel auftaucht:
https://github.com/search?q=repo%3Ardmorganiser%2Frdmo-catalog+%22When+available%22&type=code

Ich würde auch @torsten-rathmann als Erstautor involvieren.

Du kannst direkt aus der Issue einen neuen Branch anlegen (und folglich eine Merge Request)

![image](https://github.com/rdmorganiser/rdmo-catalog/assets/37865804/27fe011f-6b5e-4c2f-9456-8bc1461304be)
