### ISSUE TITLE
Trennung der Inhalte für RDMO 1.x und RDMO 2.x

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo-catalog#252]
- [x] Anlegen separater Branches --> [1.x](https://github.com/rdmorganiser/rdmo-catalog/tree/master) und [2.x](https://github.com/rdmorganiser/rdmo-catalog/tree/master-rdmo2.x)
- [x] Aktualisierung der Inhalte für RDMO 1.x auf den letzten Stand --> #259 
- [x] Anpassung der Inhalte für RDMO 2.x im Kern-RDMO --> #260
- [x] Anpassung der Inhalte für RDMO 2.x im Community-Bereich --> Rundmail
- [x] Bringen beider Branches auf den letzten Stand
- [x] Künftige Umbenennung beider Branches

**Comment by Zack-83** [comment]
@jploski @yasmindemerdash @zey @johlton @DennisFriedl
Willkommen unter den Ko-Autoren der künftigen Release :)
Sind die Informationen über euch korrekt?
https://github.com/rdmorganiser/rdmo-catalog/commit/4209c41d138a53652a931dbfb5f9729dec7ec929#diff-9b9f76394a441ff40bf8d7a0f3e0ddd7ae97abfa9a9a6abaedccf76dc4d51295L1-R123

**Comment by DennisFriedl** [comment]
sieht gut aus, danke :)

**Comment by yasmindemerdash** [comment]
Hello,

Yes the information is correct.
Thanks :)

best,
Yasmin
