### ISSUE TITLE
Horizon Europe Catalogue doesn't work

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo-catalog#264]
The catalogue cannot be imported into RDMO 2.13. Messages appear during import that attributes do not exist. The import is completed but the catalogue does not work. If you answer a question, the same answer appears in all fields.
One solution could be to export the catalogue as XML (complete) from an RDMO 2 instance, then the attributes should no longer be missing during imports.
![image](https://github.com/rdmorganiser/rdmo-catalog/assets/113421464/87a6881a-9f72-4cae-ac17-17137dbb87e1)

**Comment by chsinn** [comment]
I exported the Horizon Europe catalogue from an AIP test server as "XML (complete)", this could be imported to RDMO 2.1.3 without any problems.

**Comment by Zack-83** [comment]
@chsinn was denkst du, besteht das Problem noch oder können wir die Issue schließen?
