### ISSUE TITLE
change attribute for policy requirements in DFG checklist catalog

### ISSUE THREAD

**Issue by jwindeck** [rdmorganiser/rdmo-catalog#275]
We are currently revising the NFDI4ING catalog which is based on the DFG checklist catalog.

For the question "Are there any significant research codes or professional standards to be taken into account?" the catalog uses the attribute `https://rdmorganiser.github.io/terms/domain/project/additional_rdm_policy/yesno`, but it expects options as answers, so it's not really a yes-no question.

I found that in the RDMO catalog, two questions are connected:

"Are there requirements regarding the data management from other parties (e.g. the scholarly/scientific community)?" pointing to `https://rdmorganiser.github.io/terms/domain/project/additional_rdm_policy/yesno`

and 

"Which are these additional requirements regarding data management?" pointing to `https://rdmorganiser.github.io/terms/domain/project/additional_rdm_policy/requirements`

The second question seems expecting an answer closer to the DFG checklist question. 

So I suggest, to change the attribute to `https://rdmorganiser.github.io/terms/domain/project/additional_rdm_policy/requirements` in the DFG checklist catalog.

An alternative might be, since "additional_rdm_policy" is not quite the right wording, to introduce a new attribute like `https://rdmorganiser.github.io/terms/domain/project/rdm_policies`, but this should then be changed in other catalogs as well to ensure interoperability.

see https://github.com/rdmorganiser/rdmo-catalog/blob/6a0ad9c08e8a1475a43d0b52742f3801f0182903/rdmorganiser/questions/questions-DFG-Checkliste.xml#L857

**Comment by Zack-83** [comment]
Good idea. First attempt: https://github.com/rdmorganiser/rdmo-catalog/commit/3310b229c0073bfc093775ba901e2f4f9c5f946c Please review it, @jwindeck
