### ISSUE TITLE
No entry possible for repository in catalogue re3data.org

### ISSUE THREAD

**Issue by mkleemeyer** [rdmorganiser/rdmo-catalog#40]
When trying to answer the question "In which repository or archive will the data be held?", I can neither select from a list (although it states "select"), nor can I enter something via keyboard.

**Comment by jochenklar** [comment]
Hi @mkleemeyer , can you specify which catalog you are using? If it is using the re3data dynamic questionset, which we developed last year, the corresponding plugin needs to be installed and working.

**Comment by mkleemeyer** [comment]
Hey @jochenklar, I guess that is the problem. I am playing around with the RDMO Demo (and I am truly enthusiastic about it!!) and then picked the catalog "New feature: re3data.org". When I then added a set i got the question "In which repository or archive will the data be held?" and then was not able to continue because I could neither select nor enter and was not sure why. I was not aware that I would have to install a plugin... Thanks for your quick response!

**Comment by jochenklar** [comment]
Cool, glad you like it. The plugin needs to be installed on the server. I will ask @triole to look into it. If you are interested in RDMO feel free to join our mailing list, write me a mail to join our slack or come to our "Sprechstunde" (office hours) on the first Thursday in May (or every other month).

**Comment by jochenklar** [comment]
Hi @yvgrossmann , actually it should work with all recent versions of RDMO. Did you check if it works, or is it just about making the required version explicit?

**Comment by yvgrossmann** [comment]
Hey @jochenklar thank and good to know. We'll have a check, if it works smoothly we new RDMO versions.
BTW: The different RDMO plugins have a link to the RDMO documentation. Seems like there is no plugin sub-category in the documentation. If helpful, I could update the link to the generic one: https://rdmo.readthedocs.io/en/latest/plugins/index.html.

**Comment by yvgrossmann** [comment]
Hey @jochenklar, we tried to get the re3data plugin running, unfortunately that was not possible. I opened an issue at the plugin about that: [https://github.com/rdmorganiser/rdmo-re3data/issues/1](https://github.com/rdmorganiser/rdmo-re3data/issues/1)

**Comment by jochenklar** [comment]
I will have a look.

**Comment by yvgrossmann** [comment]
Works fine, we were able to test the re3data plugin. Both the use of an independent catalogue and the implementation in already existing catalogues via optionset re3data plus widget type "drop down" work as desired.
