### ISSUE TITLE
reference to non-existing attribute in rdmo view. 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo-catalog#53]
rdmorganiser/views/rdmo.xml references to non-existing attributes 

https://github.com/rdmorganiser/rdmo-catalog/blob/c35c1fa2c0be06c081bca6bbc422c98a8461b74e/rdmorganiser/views/rdmo.xml#L72

https://github.com/rdmorganiser/rdmo-catalog/blob/c35c1fa2c0be06c081bca6bbc422c98a8461b74e/rdmorganiser/views/rdmo.xml#L73

**Comment by Zack-83** [comment]
@jochenklar Die Ansicht `rdmo.xml` [existiert nicht mehr](https://github.com/rdmorganiser/rdmo-catalog/tree/dev/rdmorganiser/views).

![grafik](https://user-images.githubusercontent.com/37865804/140724056-7b0214da-557f-4da1-8c60-f478ca728f9e.png)

@jmfrenzel Wird die Ansicht `rdmo.xml` überhaupt gebraucht?

Horizon2020 war schon auf dem neuesten Stand. Ich habe Bielefend und SNF aktualisiert. Die anderen sind nicht betroffen.

**Comment by jochenklar** [comment]
@Zack-83 `rdmo.xml` haben wir rausgenommen, weil die views jetzt einzeln importiert werden können/müssen. Die Ansichten sind aber nur kopiert, der Fehler sollte noch in einer der Ansichten sein.

**Comment by Zack-83** [comment]
Achsooo, es war nur ein "Dach" 😅
