### ISSUE TITLE
Scripted conversion into GitHub/GitLab issues

### ISSUE THREAD

**Issue by katrinleinweber** [rdmorganiser/rdmo-catalog#9]
Seeing that version control platforms are increasingly being used in academic projects, I'd like to ask the question whether the RMDO items/questions could be made available for import into the issue trackers of these platforms.

[Both](https://developer.github.com/v3/issues/#create-an-issue) [offer](https://docs.gitlab.com/ce/api/issues.html#new-issue) issue creation APIs, whose expected data fields (JSON format) could maybe be populated as follows from RDMO's XML:

- `<text lang="...">` => `title`
- `<help lang="...">` => `body` / `description`
- `["DMP", "<key>"]` => `labels` 

Presumably, a script is needed that takes (the URL to) an RDMO-XML, a target repository and a personal access token that the user fetches from their GitHub/GitLab account and creates a bunch of DMP issues in their repo/project, which can then be adressed in parallel to the project progress. Not as a "living document", but as a conversation / discussion and [implementation](https://help.github.com/articles/closing-issues-using-keywords/) in [specific](https://docs.gitlab.com/ee/user/project/issues/automatic_issue_closing.html#default-closing-pattern-value) files in the project.

Related: https://github.com/softwaresaved/software-management-plans/issues/12

**Comment by Zack-83** [comment]
Software issue. Possibly implemented through 
https://github.com/rdmorganiser/rdmo-github and 
https://github.com/rdmorganiser/rdmo-gitlab
